/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.keremtigre;

import java.awt.BasicStroke;
import java.awt.Button;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Polygon;
import java.awt.Stroke;
import java.awt.geom.Line2D;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author Kerem
 */
public class AnaMenu extends javax.swing.JFrame {
JFrame cizimEkrani=new JFrame();
    int[] xValues;
    int[] yValues;
    public AnaMenu() {
        initComponents();
       
        //Button Gruplama
        ButtonGroup buttonGroup=new ButtonGroup();
        buttonGroup.add(radioCizgi);
        buttonGroup.add(radioNokta);
        buttonGroup.add(radioPoligon);
        
        //Button Gruplama
        ButtonGroup buttonGroup2=new ButtonGroup();
        buttonGroup2.add(radioYuvarlak);
        buttonGroup2.add(radioCarpi);
        buttonGroup2.add(radioArti);
        buttonGroup2.add(radioInce);
        buttonGroup2.add(radioNormal);
        buttonGroup2.add(radioKalin);
        buttonGroup2.add(radioIciBos);
        buttonGroup2.add(radioIciDolu);
        buttonGroup2.add(radioIciTarali);
        
        
        
        
     
                
    }
    //Çizgi Çizme Fonksiyonu
    
    public void cizgiCiz(int kalinlik){
        
        Graphics g=jPanel1.getGraphics();
       Graphics2D g2=(Graphics2D)g;
       g2.draw(new Line2D.Float(xValues[0], yValues[0],xValues[1],yValues[1]));
                    
                
    }
    //İçi Boş Poligon Çizme Fonksiyonu
    public void poligonCiz(){
        Graphics g=jPanel1.getGraphics();
       Graphics2D g2=(Graphics2D)g;
       g2.drawPolygon(xValues, yValues, xValues.length);
       
    }
    //İçi Dolu Poligon Çizme Fonksiyonu
     public void poligonCiz2(){
        Graphics g=jPanel1.getGraphics();
       Graphics2D g2=(Graphics2D)g;
       g2.fillPolygon(new Polygon(xValues, yValues, xValues.length));
     
    }
     
     //yuvarlak nokta çizme fonksiyonu
      public void noktaCiz(){
        Graphics g=jPanel1.getGraphics();
       Graphics2D g2=(Graphics2D)g;
       g2.fillOval(xValues[0], yValues[0], 10,10);
     
    }
      //X nokta çizme fonksiyonu
   public void noktaCiz2(){
        Graphics g=jPanel1.getGraphics();
       Graphics2D g2=(Graphics2D)g;
       g2.setStroke(new BasicStroke(3));
     g.drawLine(xValues[0], yValues[0], xValues[0]+10,yValues[0]+10);
g.drawLine(xValues[0]+10, yValues[0], xValues[0], yValues[0]+10);
    }
   //Artı nokta çizme fonksiyonu
   public void noktaCiz3(){
       Graphics g=jPanel1.getGraphics();
       Graphics2D g2=(Graphics2D)g;
       g2.setStroke(new BasicStroke(3));
        g2.drawLine(xValues[0], yValues[0] - 5, xValues[0], yValues[0] + 5);
        g2.drawLine(xValues[0] + 5, yValues[0], xValues[0] - 5, yValues[0]);
   
   }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cizimAlaniGenislik = new javax.swing.JTextField();
        cizimAlaniYukseklik = new javax.swing.JTextField();
        panelOlusturButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        radioNokta = new javax.swing.JRadioButton();
        radioInce = new javax.swing.JRadioButton();
        radioCizgi = new javax.swing.JRadioButton();
        radioNormal = new javax.swing.JRadioButton();
        radioPoligon = new javax.swing.JRadioButton();
        radioKalin = new javax.swing.JRadioButton();
        radioYuvarlak = new javax.swing.JRadioButton();
        radioIciBos = new javax.swing.JRadioButton();
        radioCarpi = new javax.swing.JRadioButton();
        radioIciDolu = new javax.swing.JRadioButton();
        radioArti = new javax.swing.JRadioButton();
        radioIciTarali = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ekleButton = new javax.swing.JButton();
        koordinatBilgiLabel = new javax.swing.JLabel();
        xKoordinatGiris = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        yKoordinatGiris = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMaximumSize(new java.awt.Dimension(1451, 560));
        jPanel1.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1496, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Çizim Alanının Boyutlarını Giriniz ");

        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Genişlik");

        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Yükseklik");

        panelOlusturButton.setBackground(new java.awt.Color(255, 153, 153));
        panelOlusturButton.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        panelOlusturButton.setForeground(new java.awt.Color(255, 255, 255));
        panelOlusturButton.setText("Oluştur");
        panelOlusturButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panelOlusturButtonActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("1500");

        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("560");

        radioNokta.setForeground(new java.awt.Color(240, 240, 240));
        radioNokta.setText("Nokta ");

        radioInce.setForeground(new java.awt.Color(240, 240, 240));
        radioInce.setText("İnce");

        radioCizgi.setForeground(new java.awt.Color(240, 240, 240));
        radioCizgi.setText("Çizgi");

        radioNormal.setForeground(new java.awt.Color(240, 240, 240));
        radioNormal.setText("Normal");

        radioPoligon.setForeground(new java.awt.Color(240, 240, 240));
        radioPoligon.setText("Poligon");

        radioKalin.setForeground(new java.awt.Color(240, 240, 240));
        radioKalin.setText("Kalın");

        radioYuvarlak.setForeground(new java.awt.Color(240, 240, 240));
        radioYuvarlak.setText("Yuvarlak");

        radioIciBos.setForeground(new java.awt.Color(240, 240, 240));
        radioIciBos.setText("İçi Boş");

        radioCarpi.setForeground(new java.awt.Color(240, 240, 240));
        radioCarpi.setText("Çarpı");

        radioIciDolu.setForeground(new java.awt.Color(240, 240, 240));
        radioIciDolu.setText("İçi Dolu");

        radioArti.setForeground(new java.awt.Color(240, 240, 240));
        radioArti.setText("Artı");

        radioIciTarali.setForeground(new java.awt.Color(240, 240, 240));
        radioIciTarali.setText("İçi Taralı");

        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Çizmek İstediğiniz Şekil");

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Çizeceğiniz Şeklin Türü ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cizimAlaniGenislik)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cizimAlaniYukseklik)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(panelOlusturButton))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(radioNokta)
                            .addGap(26, 26, 26)
                            .addComponent(radioCizgi, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(radioPoligon, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(radioYuvarlak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radioArti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radioCarpi, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(radioNormal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radioKalin, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                .addComponent(radioInce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(radioIciBos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radioIciDolu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radioIciTarali, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cizimAlaniGenislik)
                    .addComponent(cizimAlaniYukseklik)
                    .addComponent(panelOlusturButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioNokta)
                    .addComponent(radioCizgi)
                    .addComponent(radioPoligon)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(radioYuvarlak, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioCarpi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioArti))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(radioInce)
                        .addGap(21, 21, 21)
                        .addComponent(radioKalin))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(radioNormal))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(radioIciTarali))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(radioIciBos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioIciDolu)))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ekleButton.setBackground(new java.awt.Color(255, 153, 153));
        ekleButton.setForeground(new java.awt.Color(255, 255, 255));
        ekleButton.setText("Ekle");
        ekleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleButtonActionPerformed(evt);
            }
        });

        koordinatBilgiLabel.setForeground(new java.awt.Color(240, 240, 240));
        koordinatBilgiLabel.setText("Verilerin arasında boşluk olmaladır örneğin(5.8 20 30 gibi...)");

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("X Koordinatlarını sırasıyla giriniz");

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Y Koordinatlarını sırasıyla giriniz");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(koordinatBilgiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(xKoordinatGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(yKoordinatGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 17, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(ekleButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xKoordinatGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yKoordinatGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(koordinatBilgiLabel)
                .addGap(28, 28, 28)
                .addComponent(ekleButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Source Code Pro Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Desinged by @keremtigre");

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("DialogInput", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Bu Uygulama ile belirtilen seçeneklerde basit çizimler yapabilirsiniz. ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 32, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel12.setFont(new java.awt.Font("Source Code Pro Black", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Github: @keremtigre");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelOlusturButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panelOlusturButtonActionPerformed
        //panel ayarlanıyor

        // panali +10 daha büyük oluşturdum. Çünkü bu sefer panelin köşeleri koordinat olarak verilirse noktadaki yuvarlak ,artı,çarpı türleri alanın dışında kalıyor.Fonksiyondan kaynaklı
        jPanel1.setSize((Integer.parseInt(cizimAlaniGenislik.getText()))+10, (Integer.parseInt(cizimAlaniYukseklik.getText()))+10);
        jPanel1.setBackground(Color.WHITE);

    }//GEN-LAST:event_panelOlusturButtonActionPerformed

    private void ekleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleButtonActionPerformed

        //X ve Y değerlerini Diziye Aktarıyoruz
        String xValuesText=xKoordinatGiris.getText();
        String[] xValuesTextArray = xValuesText.split(" ");
        xValues = new int[xValuesTextArray.length];

        for(int i = 0; i < xValuesTextArray.length; i++) {
            try {
                xValues[i] = Integer.parseInt(xValuesTextArray[i]);
            } catch (NumberFormatException nfe) {

            }

        }

        String yValuesText=yKoordinatGiris.getText();
        String[] yValuesTextArray = yValuesText.split(" ");
        yValues = new int[yValuesTextArray.length];

        for(int i = 0; i < yValuesTextArray.length; i++) {
            try {
                yValues[i] = Integer.parseInt(yValuesTextArray[i]);
            } catch (NumberFormatException nfe) {

            }

        }
        //Bitiş
        System.out.println(""+xValues.length);
        System.out.println(""+yValues.length);

        //Durumları kontrol edip Çizdirme İşlemleri
        if(radioCizgi.isSelected() && radioInce.isSelected()){
            cizgiCiz(2);
        }
        else if(radioCizgi.isSelected() && radioNormal.isSelected()){
            cizgiCiz(6);
        }
        else if(radioCizgi.isSelected() && radioKalin.isSelected()){

            cizgiCiz(10);
        }
        else if(radioPoligon.isSelected() && radioIciBos.isSelected()){
            poligonCiz();
        }
        else if(radioPoligon.isSelected() && radioIciDolu.isSelected()){
            poligonCiz2();
        }
        else if (radioPoligon.isSelected() && radioIciTarali.isSelected()) {
            JOptionPane.showMessageDialog(this, "OOPS !! Sıkıntı Oluştu");
        }
        else if (radioNokta.isSelected() && radioYuvarlak.isSelected()) {
            noktaCiz();
        }
        else if (radioNokta.isSelected() && radioCarpi.isSelected()) {
            noktaCiz2();
        }
        else if (radioNokta.isSelected() && radioArti.isSelected()) {
            noktaCiz3();
        }

    }//GEN-LAST:event_ekleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cizimAlaniGenislik;
    private javax.swing.JTextField cizimAlaniYukseklik;
    private javax.swing.JButton ekleButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel koordinatBilgiLabel;
    private javax.swing.JButton panelOlusturButton;
    private javax.swing.JRadioButton radioArti;
    private javax.swing.JRadioButton radioCarpi;
    private javax.swing.JRadioButton radioCizgi;
    private javax.swing.JRadioButton radioIciBos;
    private javax.swing.JRadioButton radioIciDolu;
    private javax.swing.JRadioButton radioIciTarali;
    private javax.swing.JRadioButton radioInce;
    private javax.swing.JRadioButton radioKalin;
    private javax.swing.JRadioButton radioNokta;
    private javax.swing.JRadioButton radioNormal;
    private javax.swing.JRadioButton radioPoligon;
    private javax.swing.JRadioButton radioYuvarlak;
    private javax.swing.JTextField xKoordinatGiris;
    private javax.swing.JTextField yKoordinatGiris;
    // End of variables declaration//GEN-END:variables
}
